"""Add user_id to vehicle_sold table

Revision ID: 017e0496b117
Revises: 2eaf7fef07a8
Create Date: 2024-06-06 00:12:04.075255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017e0496b117'
down_revision: Union[str, None] = '2eaf7fef07a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_sold', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_sold', 'user_id')
    # ### end Alembic commands ###
