"""update sold vehicle table with enum

Revision ID: 38567dcbd1da
Revises: e3880185855d
Create Date: 2024-06-19 01:28:11.563531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38567dcbd1da'
down_revision: Union[str, None] = 'e3880185855d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_sold', 'status',
               existing_type=postgresql.ENUM('draft', 'sold', name='status_enum'),
               type_=sa.Enum('draft', 'sold', name='status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_sold', 'status',
               existing_type=sa.Enum('draft', 'sold', name='status_enum'),
               type_=postgresql.ENUM('draft', 'sold', name='status_enum'),
               existing_nullable=False)
    # ### end Alembic commands ###
